task_1_cases = [
    {
        "numbers": [],
        "result": 0,
    },
    {
        "numbers": [1, 2, 3, 4, 5],
        "result": 0,
    },
    {
        "numbers": [0, 0, 0, 0],
        "result": 4,
    },
    {
        "numbers": [1, 0, 2, 0, 3, 0],
        "result": 3,
    },
    {
        "numbers": [-5, 0, -1, 8, 0, 10, -7],
        "result": 2,
    },
]
task_2_cases = [
    {
        "number": 1,
        "result": 1,
    },
    {
        "number": 2,
        "result": 2,
    },
    {
        "number": 3,
        "result": 2,
    },
    {
        "number": 4,
        "result": 3,
    },
    {
        "number": 6,
        "result": 4,
    },
    {
        "number": 12,
        "result": 6,
    },
    {
        "number": 25,
        "result": 3,
    },
    {
        "number": 36,
        "result": 9,
    },
    {
        "number": 97,
        "result": 2,
    },
    {
        "number": 2000000000,
        "result": 110,
    },
]
task_3_cases = [
    {
        "start": 2,
        "end": 4,
        "result": [2, 4],
    },
    {
        "start": 2,
        "end": 5,
        "result": [2, 4],
    },
    {
        "start": 0,
        "end": 10,
        "result": [0, 2, 4, 6, 8, 10],
    },
    {
        "start": 11,
        "end": 11,
        "result": [],
    },
    {
        "start": 1,
        "end": 101,
        "result": [
            2,
            4,
            6,
            8,
            10,
            12,
            14,
            16,
            18,
            20,
            22,
            24,
            26,
            28,
            30,
            32,
            34,
            36,
            38,
            40,
            42,
            44,
            46,
            48,
            50,
            52,
            54,
            56,
            58,
            60,
            62,
            64,
            66,
            68,
            70,
            72,
            74,
            76,
            78,
            80,
            82,
            84,
            86,
            88,
            90,
            92,
            94,
            96,
            98,
            100,
        ],
    },
]
